### ISSUE TITLE
transmission doesn't work

### ISSUE THREAD

**Issue by djpoldino** [JamesP6000/PiCW#3]
hi! i've compiling with 4.9.
the program works.
It writes "TRASMITTING E E E E" (for example) but on oscilloscope i don't see nothing.
i try also with cw receiver and it's the same.
have u got some idea?
Raspberry PI 3
73's IU5FRT

**Comment by JamesP6000** [comment]
I haven't tried it on an RPi 3 yet :( I'm guessing it does not work on that
version :( :(

James

**Comment by djpoldino** [comment]
Ok. I try on raspberry one. Thank you very much!

Il 09 Ott 2016 19:26, "James Peroulas" notifications@github.com ha
scritto:

**Comment by djpoldino** [comment]
Doesn't work on rasp 1.
The same thing.

**Comment by JamesP6000** [comment]
Very odd... I developed the code on an RPi 1... I wonder if something has
changed? Are you using Raspbian? Is it possible you're not observing the
correct GPIO on the output of the Pi? The GPIO number is not the same as
the pin number.

JP

**Comment by djpoldino** [comment]
Using raspbian(the last).
Antenna is on pin 7 (gpio 4) and 9(gnd).
No solution? :(

**Comment by JamesP6000** [comment]
That's very interesting... Does PiFM also not work on the latest Raspbian?
This code descends from PiFM.

James

**Comment by djpoldino** [comment]
I'll try the PiFm.
Wait some days.
At now,Tanks for you help!

Il 25 Ott 2016 20:28, "James Peroulas" notifications@github.com ha
scritto:

> That's very interesting... Does PiFM also not work on the latest Raspbian?
> This code descends from PiFM.
> 
> James
>

**Comment by JamesP6000** [comment]
I just freshened the code. Please have a try. The code now works for RPi2/3 in addition to RPi1!

**Comment by djpoldino** [comment]
Ok.sorry if i did not replay you. But cause job, I had not any time in this
months for try it. But when i have something time i tell you about it.
Thanks again!

Il 03 Mar 2017 07:10, "James Peroulas" <notifications@github.com> ha
scritto:
