### ISSUE TITLE
Wrong frequency

### ISSUE THREAD

**Issue by michelinok** [JamesP6000/PiCW#4]
Hi!
I think i've found a bug...
If i specify -f 702300  it transmit on 7.023Mhz  ...is it right or wrong?

**Comment by JamesP6000** [comment]
Hi,

The frequency is specified on the command line in Hz, so this is what
should be happening. What did you expect?

JP

**Comment by michelinok** [comment]
from 702300 i would expect 0.7023 and not 7.023

**Comment by JamesP6000** [comment]
Oh, sorry, i misread you email! Do other frequencies work properly? I
wonder if there is a lower limit of operation. Strange that it would be off
by exactly a factor of 10. Hmm..

JP

**Comment by michelinok** [comment]
i've tested only 40m and 20m and the problem is on all the 2 bands i've tested

**Comment by michelinok** [comment]
and of course...also the text output (let me call it "info") is "wrong" (it's ok because if the rpi tx on 0.7 the output on the video is 0.7...instead it should tx on 7 and display 7...sorry for my english!)

**Comment by JamesP6000** [comment]
Can you try 10140200 and 10.140200e6? Those are the frequencies i developed
the software on.

Some other things:
How are you measuring the output frequency?
Try turning off the ntp based frequency correction.
I developed the code on a raspberry pi 1. Are you using a different version?

JP

**Comment by michelinok** [comment]
i'll try tomorrow, sorry...having a birthday today :)

**Comment by JamesP6000** [comment]
Hi, I recently tested this out and I was able to produce 702.300 kHz with a Raspberry Pi v1. This was measured with an external frequency counter.

Here is the command I used:
`sudo ./PiCW --test-tone -f 0.7023e6 -s`

Are you still having problems?

James
