### ISSUE TITLE
Why not a full-blown CW TRX?

### ISSUE THREAD

**Issue by ghost** [JamesP6000/PiCW#5]
Now that this code is done, why not extend it to be a full-blown CW TRX? I can imagine something like:

Connect a straight key to GPIO X.
```
If GPIO X
  send tone
end if
```

Or even:

Connect iambic keyer to GPIO X and Y.
```
Case GPIO
  X
    send dit
    sleep
  Y
    send dah
    sleep
  X+Y
    send dit
    sleep
    send dah
    sleep
End case
```

SDR can be used to listen for response.

**Comment by JamesP6000** [comment]
I certainly would like to integrate an SDR receier, say with an RTL* dongle. That's much more of a long term project though :) First I want to get this running on the RPI2/3.

**Comment by JamesP6000** [comment]
Now working on RPI2/3 :)
